<?php

namespace Proxy\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TipoUsuario extends \App\Entity\TipoUsuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'ativo', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'criadoEm', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'alteradoEm', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'deletadoEm'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'tipo', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'ativo', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'criadoEm', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'alteradoEm', '' . "\0" . 'App\\Entity\\TipoUsuario' . "\0" . 'deletadoEm'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TipoUsuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo(string $tipo): \App\Entity\TipoUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function isAtivo(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAtivo', []);

        return parent::isAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo(bool $ativo): \App\Entity\TipoUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCriadoEm(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCriadoEm', []);

        return parent::getCriadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCriadoEm(): \App\Entity\TipoUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCriadoEm', []);

        return parent::setCriadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlteradoEm(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlteradoEm', []);

        return parent::getAlteradoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlteradoEm(): \App\Entity\TipoUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlteradoEm', []);

        return parent::setAlteradoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletadoEm(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletadoEm', []);

        return parent::getDeletadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletadoEm(): \App\Entity\TipoUsuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletadoEm', []);

        return parent::setDeletadoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
